version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_container
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          cpus: '1.0'   # Limita a 1 CPU
          memory: 2g    # Limita a 2GB de RAM
    volumes:
      - ./mssql_data:/var/opt/mssql

volumes:
  mssql_data:
